export interface Category {
  id: string;
  name: string;
  emoji: string;
  color: string;
  bgColor: string;
  themes: string[];
}

export const categories: Category[] = [
  {
    id: "dinosaurs",
    name: "Dinosaurs",
    emoji: "🦕",
    color: "#2d8a4e",
    bgColor: "#d4edda",
    themes: [
      "friendly T-Rex who loves to dance",
      "baby triceratops looking for friends",
      "pterodactyl who is afraid of heights",
      "brontosaurus who discovers a magical garden",
      "stegosaurus who wants to be a chef",
      "velociraptor who loves painting",
      "baby dinosaur hatching from an egg",
      "dinosaur school where they learn to roar",
    ],
  },
  {
    id: "animals",
    name: "Animals",
    emoji: "🐶",
    color: "#8B4513",
    bgColor: "#fde8d0",
    themes: [
      "puppy who goes on a big adventure",
      "kitten who makes a new friend",
      "bunny who plants a magical garden",
      "baby elephant learning to use their trunk",
      "little bear who discovers honey",
      "penguin who dreams of flying",
      "baby giraffe who feels too tall",
      "friendly dolphin who helps lost fish",
    ],
  },
  {
    id: "cars",
    name: "Cars",
    emoji: "🚗",
    color: "#dc3545",
    bgColor: "#f8d7da",
    themes: [
      "little red car on a big road trip",
      "race car who learns about teamwork",
      "fire truck saving the day",
      "ambulance helping everyone",
      "friendly bus picking up happy passengers",
      "police car on a rescue mission",
      "ice cream truck spreading joy",
      "little car learning to be brave",
    ],
  },
  {
    id: "construction",
    name: "Construction",
    emoji: "🏗️",
    color: "#f0ad4e",
    bgColor: "#fff3cd",
    themes: [
      "excavator digging for treasure",
      "crane building the tallest tower",
      "bulldozer clearing the way for a playground",
      "cement mixer making the best birthday cake (out of cement!)",
      "dump truck delivering surprise presents",
      "construction crew building a treehouse",
      "wrecking ball who is gentle",
      "team of machines building a castle",
    ],
  },
  {
    id: "farm",
    name: "Farm",
    emoji: "🚜",
    color: "#28a745",
    bgColor: "#d4edda",
    themes: [
      "tractor plowing magical fields",
      "baby chick hatching adventure",
      "cow who gives chocolate milk",
      "pig who loves mud puddle parties",
      "sheep who has the fluffiest wool",
      "rooster who oversleeps",
      "combine harvester at harvest festival",
      "farm animals throwing a barn dance",
    ],
  },
  {
    id: "space",
    name: "Space",
    emoji: "🚀",
    color: "#6f42c1",
    bgColor: "#e8daef",
    themes: [
      "rocket ship flying to the moon",
      "friendly alien who visits Earth",
      "astronaut floating in space",
      "stars that play hide and seek",
      "planet made entirely of candy",
      "space station with a garden",
      "comet racing through the sky",
      "moon who wants a friend",
    ],
  },
  {
    id: "airplanes",
    name: "Airplanes",
    emoji: "✈️",
    color: "#17a2b8",
    bgColor: "#d1ecf1",
    themes: [
      "little airplane on their first flight",
      "helicopter rescue mission",
      "hot air balloon floating over the world",
      "paper airplane that flies everywhere",
      "airplane that writes messages in the sky",
      "biplane doing loop-de-loops",
      "seaplane landing on a lake",
      "jet that delivers birthday presents around the world",
    ],
  },
  {
    id: "ocean",
    name: "Ocean",
    emoji: "🐳",
    color: "#0056b3",
    bgColor: "#cce5ff",
    themes: [
      "whale who sings beautiful songs",
      "little fish finding a treasure chest",
      "octopus who gives the best hugs",
      "sea turtle on a journey",
      "submarine exploring the deep sea",
      "starfish who grants wishes",
      "crab building sandcastles",
      "mermaid and the underwater party",
    ],
  },
  {
    id: "castle",
    name: "Knights",
    emoji: "🏰",
    color: "#6c757d",
    bgColor: "#e2e3e5",
    themes: [
      "brave knight rescuing a friendly dragon",
      "princess who builds her own castle",
      "dragon who breathes bubbles instead of fire",
      "wizard with a silly magic wand",
      "enchanted forest with talking trees",
      "castle with secret passages",
      "unicorn who loves rainbow slides",
      "tiny knight and the big adventure",
    ],
  },
  {
    id: "superheroes",
    name: "Heroes",
    emoji: "🦸",
    color: "#e83e8c",
    bgColor: "#f8d7e8",
    themes: [
      "superhero who can talk to animals",
      "hero with super-speed helping everyone",
      "hero who makes everyone laugh",
      "superhero team cleaning up the park",
      "hero whose superpower is kindness",
      "flying hero delivering cookies",
      "invisible hero who loves surprises",
      "hero with super-strong hugs",
    ],
  },
  {
    id: "trains",
    name: "Trains",
    emoji: "🚂",
    color: "#495057",
    bgColor: "#e9ecef",
    themes: [
      "little train climbing the big mountain",
      "express train delivering presents",
      "train station where everyone says hello",
      "steam train chugging through a magical land",
      "monorail in a futuristic city",
      "toy train that comes alive",
      "freight train carrying surprise cargo",
      "train that runs on rainbows",
    ],
  },
  {
    id: "bugs",
    name: "Bugs",
    emoji: "🐛",
    color: "#20c997",
    bgColor: "#d2f4ea",
    themes: [
      "caterpillar becoming a butterfly",
      "ladybug counting her spots",
      "firefly lighting up the night",
      "ant who carries the biggest crumb",
      "bee making the sweetest honey",
      "spider spinning a beautiful web",
      "dragonfly racing the wind",
      "cricket singing a bedtime song",
    ],
  },
];
